apiVersion: v1
kind: Pod
metadata:
  labels:
    app: knowhere-cpu-build
  namespace: knowhere-ci
spec:
  enableServiceLinks: false
  nodeSelector:
    app: knowhere
  containers:
  - name: main
    image: harbor.milvus.io/dockerhub/milvusdb/knowhere-cpu-build:amd64-ubuntu20.04-20220914-30a5e60
    tty: true
    args: ["cat"]
    resources:
      limits:
        memory: "4Gi"
        cpu: "8"
      requests:
        memory: "1Gi"
        cpu: "3"
